/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.0.2.0                                               */
/*  Date (dd.mm.yyyy): 12. 9.2020   Time (hh:mm): 17:15                        */
/*******************************************************************************/


#ifndef _SPORTS_GOAL_DISPLAY_1_RESOURCES_H_
#define _SPORTS_GOAL_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 320
#define DISPLAY_1_Y_RESOLUTION 385
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BACK1_YELLOW 5
#define GX_PIXELMAP_ID_BACK_GRAY 6
#define GX_PIXELMAP_ID_BATTERY_0 7
#define GX_PIXELMAP_ID_BATTERY_1 8
#define GX_PIXELMAP_ID_BATTERY_2 9
#define GX_PIXELMAP_ID_BATTERY_3 10
#define GX_PIXELMAP_ID_BATTERY_4 11
#define GX_PIXELMAP_ID_BATTERY_5 12
#define GX_PIXELMAP_ID_CALORIES_WHITE_TEXT 13
#define GX_PIXELMAP_ID_CALORIES_YELLOW_TEXT 14
#define GX_PIXELMAP_ID_DISTANCE_WHITE_TEXT 15
#define GX_PIXELMAP_ID_DISTANCE_YELLOW_TEXT 16
#define GX_PIXELMAP_ID_GOAL_CALORIES_TEXT 17
#define GX_PIXELMAP_ID_GOAL_COMPLETE_TEXT 18
#define GX_PIXELMAP_ID_GOAL_COUNTDOWN_TEXT 19
#define GX_PIXELMAP_ID_GOAL_DURATION_TEXT 20
#define GX_PIXELMAP_ID_GOAL_MIN_TEXT 21
#define GX_PIXELMAP_ID_GOAL_SETTING_TEXT 22
#define GX_PIXELMAP_ID_KACL_YELLOW_TEXT 23
#define GX_PIXELMAP_ID_LIST_ARROW 24
#define GX_PIXELMAP_ID_MIN_WHITE_TEXT 25
#define GX_PIXELMAP_ID_SPORTS1_NUM0 26
#define GX_PIXELMAP_ID_SPORTS1_NUM1 27
#define GX_PIXELMAP_ID_SPORTS1_NUM10 28
#define GX_PIXELMAP_ID_SPORTS1_NUM2 29
#define GX_PIXELMAP_ID_SPORTS1_NUM3 30
#define GX_PIXELMAP_ID_SPORTS1_NUM4 31
#define GX_PIXELMAP_ID_SPORTS1_NUM5 32
#define GX_PIXELMAP_ID_SPORTS1_NUM6 33
#define GX_PIXELMAP_ID_SPORTS1_NUM7 34
#define GX_PIXELMAP_ID_SPORTS1_NUM8 35
#define GX_PIXELMAP_ID_SPORTS1_NUM9 36
#define GX_PIXELMAP_ID_SPORTS2_NUM0 37
#define GX_PIXELMAP_ID_SPORTS2_NUM1 38
#define GX_PIXELMAP_ID_SPORTS2_NUM2 39
#define GX_PIXELMAP_ID_SPORTS2_NUM3 40
#define GX_PIXELMAP_ID_SPORTS2_NUM4 41
#define GX_PIXELMAP_ID_SPORTS2_NUM5 42
#define GX_PIXELMAP_ID_SPORTS2_NUM6 43
#define GX_PIXELMAP_ID_SPORTS2_NUM7 44
#define GX_PIXELMAP_ID_SPORTS2_NUM8 45
#define GX_PIXELMAP_ID_SPORTS2_NUM9 46
#define GX_PIXELMAP_ID_TARGET_BACK 47
#define GX_PIXELMAP_ID_TARGET_CALORIES_BACK 48
#define GX_PIXELMAP_ID_TARGET_CLOSE_ICON 49
#define GX_PIXELMAP_ID_TARGET_DISTANCE2_BACK__2_ 50
#define GX_PIXELMAP_ID_TARGET_DISTANCE_BACK 51
#define GX_PIXELMAP_ID_TARGET_KACL_BACK 52
#define GX_PIXELMAP_ID_TARGET_METER_TEXT 53
#define GX_PIXELMAP_ID_TARGET_MINUS_ICON 54
#define GX_PIXELMAP_ID_TARGET_OPEN_ICON 55
#define GX_PIXELMAP_ID_TARGET_PLUS_ICON 56
#define GX_PIXELMAP_ID_TARGET_TIME2_BACK 57
#define GX_PIXELMAP_ID_TARGET_TIME_BACK 58
#define GX_PIXELMAP_ID_TARGET_WHITE_TEXT 59
#define GX_PIXELMAP_ID_TARGET_YELLOW_TEXT 60
#define GX_PIXELMAP_ID_TIME_WHITE_TEXT 61
#define GX_PIXELMAP_ID_TIME_YELLOW_TEXT 62
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 63

/* String Ids                                                                  */

#define DISPLAY_1_STRING_TABLE_SIZE 1

#endif                                       /* sentry                         */
